INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Szymon', 'Nowak', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Anna','Kowalska','FEMALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Jan', 'Wisniewski', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Adam', 'Malysz', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Jacek', 'Haas', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Anita','Cygan','FEMALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Jarosław', 'Wawer', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Adriana', 'Plesz', 'FEMALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Szymon', 'Nowak', 'MALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Iza','Karwowska','FEMALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Justyna', 'Adamczyk', 'FEMALE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Zofia', 'Miłosz', 'FEMALE');


INSERT INTO ADDRESS (CITY, STREET) VALUES ('Poznan', 'Mickiewicza');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Dublin', 'Dorset');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Wrocłąw', 'Złotoryjska');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Warszawa', 'Woronicza');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Las Angeles', 'Bulevar Ave');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('London', 'Essex St');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Berlin', 'Gross St');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Kraków', 'Zamkowa');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Cork', 'Hunters Meadow');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Dublin', 'Rathmines st');

INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (1,1);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (2,2);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (3,1);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (4,2);

INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('wyjsc z psem', 'Lorem ipsum', 'DONE');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('wyniesc smieci', 'Lorem ipsum', 'DONE');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('ugotowac obiad', 'Lorem ipsum', 'NEW');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('napisac cv', 'Lorem ipsum', 'IN_PROGRESS');



